In [10]:
import pandas as pd

df=pd.read_csv("jems.csv")

df.set_index("Film").head()

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,59.9,...,0,0,0,9.5,4,Toyota,117,June,PG,0

In [31]:
import pandas as pd

df=pd.read_csv("jems.csv")

df.ix["Dr. No","Bond actor"]="ANKush"
df.ix["Dr. No"]

c:\users\ankush\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
c:\users\ankush\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

Film                                 NaN
Year                                 NaN
Years lapse                          NaN
Bond actor                        ANKush
Bond actor appearance                NaN
Villians Dispatched                  NaN
Others' Dispatched                   NaN
Total Dispatched                     NaN
Adjusted box office                  NaN
Actual box office                    NaN
Adjusted budget                      NaN
Actual budget                        NaN
Director                             NaN
Rotten Tomatoes critic score         NaN
Rotten Tomatoes audience score       NaN
Golden Globe nominations             NaN
Golden Globe wins                    NaN
Academy Award nominations            NaN
Academy Award wins                   NaN
Number of Bond drinks                NaN
Bond girls                           NaN
Bond car make                        NaN
Runtime minutes                      NaN
Month released                       NaN
Rating                               NaN
Bond, James Bond said                NaN
Name: Dr. No, dtype: object