In [26]:
import pandas as pd

df=pd.read_csv("pokemon.csv",index_col="Name")
df.head()

   
df.columns=[col_name.replace(" ","_")for col_name in df.columns]   
df.head()

,#,Type_1,Type_2,HP,Attack,Defense,Sp._Atk,Sp._Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,80,82,83,100,100,80,1,False
Mega Venusaur,4,Grass,Poison,80,100,123,122,120,80,1,False
Charmander,5,Fire,NaN,39,52,43,60,50,65,1,False

In [28]:
def ank(row):
    Type_1=row[2]
    HP=row[4]
    
    if Type_1=="Grass":
        return "hello i am good "
    
    elif Type_1 =="Fire" and HP >47:
        
        
        return "ohh fuck "
    else:
        return "ohh yahhhh"
    
[df.apply(ank,axis="columns")

KeyError: "None of [Index(['ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh',\n       'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh',\n       ...\n       'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh',\n       'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh', 'ohh yahhhh'],\n      dtype='object', length=800)] are in the [columns]"